webappUrl: http://localhost

logLevel: debug

fakeS3: true

graphql:
  graphiql: true

elasticsearch: 
  url: http://elastic:changeme@elasticsearch:9200

auth:
  accessTokenLifetimeInSeconds: 3600

aws:
  dynamodb:
    endpoint: 'http://dynamodb:8000'
  dynamodbstreams:
    endpoint: 'http://dynamodb:8000'
  s3ForcePathStyle: true
  s3:
    endpoint: 'http://s3:5000'
    sslEnabled: false
    s3ForcePathStyle: true

waitFor:
  timeout: 60000
  spacing: 1500

eventStreamServer:
  pollDelay: 500
